<?php

namespace AppBundle\Repository;

/**
 * ContentTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentTypeRepository extends \Doctrine\ORM\EntityRepository
{
	
	public function findAllAsAssociativeArray(){
		$qb = $this->createQueryBuilder('ct');
		$qb->where($qb->expr()->eq('ct.deleted', 0));
		
		$out = [];
		$result = $qb->getQuery()->getResult();
		/** @var \AppBundle\Entity\ContentType $record */
		foreach ($result as $record){
			$out[$record->getName()] = $record;
		}
		
		return $out;
	}
}
