<?php

namespace AppBundle\Repository;

/**
 * I18nRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class I18nRepository extends \Doctrine\ORM\EntityRepository
{
	public function count() {
		return $this->createQueryBuilder('i')
		->select('COUNT(i)')
		->getQuery()
		->getSingleScalarResult();
	}
}
