<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Revision;
use AppBundle\Entity\Environment;
use AppBundle\Entity\ContentType;

/**
 * RevisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RevisionRepository extends \Doctrine\ORM\EntityRepository
{
	
	public function draftCounterGroupedByContentType() {

		$qb = $this->createQueryBuilder('r');
		$qb->select('c.id content_type_id', 'count(c.id) counter');
		$qb->join('r.contentType', 'c');
		$and = $qb->expr()->andX();
		$and->add($qb->expr()->eq('r.deleted', 0));
		$and->add($qb->expr()->eq('r.draft', true));
		$qb->where($and);
		$qb->groupBy('c.id');
		
		return $qb->getQuery()->getResult();
	}

	public function countByContentType(ContentType $contentType) {
		return $this->createQueryBuilder('a')
		->select('COUNT(a)')
		->where('a.contentType = :contentType')
		->setParameter('contentType', $contentType)
		->getQuery()
		->getSingleScalarResult();
	}
	
	public function getAllRevisionsSummary($ouuid, ContentType $contentType) {
	
		$qb = $this->createQueryBuilder('r');
		$qb->select('r', 'e');
		$qb->leftJoin('r.environments', 'e');
		$qb->where($qb->expr()->eq('r.ouuid', ':ouuid'));
		$qb->andWhere($qb->expr()->eq('r.contentType', ':contentType'));
		$qb->orderBy('r.created', 'ASC');
		$qb->setParameter('ouuid', $ouuid);
		$qb->setParameter('contentType', $contentType);
	
		return $qb->getQuery()->getResult();
	}

	public function findByOuuidContentTypeAndEnvironnement(Revision $revision, Environment $env=null) {
	
		if(!isset($env)){
			$env = $revision->getContentType()->getEnvironment();
		}
		
		$qb = $this->createQueryBuilder('r');
		$qb->join('r.environments', 'e');
		$qb->where('r.ouuid = :ouuid and e.id = :envId and r.contentType = :contentTypeId');
		$qb->setParameters([
				'ouuid' => $revision->getOuuid(),
				'envId' => $env->getId(),
				'contentTypeId' => $revision->getContentType()->getId()
		]);
	
		return $qb->getQuery()->getResult();
	}
	

	public function lockRevision($revisionId, $username,\DateTime $lockUntil) {
		$qb = $this->createQueryBuilder('r')->update() 
			->set('r.lockBy', '?1') 
			->set('r.lockUntil', '?2') 
			->where('r.id = ?3')
			->setParameter(1, $username)
			->setParameter(2, $lockUntil, \Doctrine\DBAL\Types\Type::DATETIME)
			->setParameter(3, $revisionId);
		return $qb->getQuery()->execute();
	}

	public function finaliseRevision(ContentType $contentType, $ouuid,\DateTime $now) {
		$qb = $this->createQueryBuilder('r')->update()
			->set('r.endTime', '?1')
			->where('r.contentType = ?2')
			->andWhere('r.ouuid = ?3')
			->andWhere('r.endTime is null')
			->setParameter(1, $now, \Doctrine\DBAL\Types\Type::DATETIME)
			->setParameter(2, $contentType)
			->setParameter(3, $ouuid);
		return $qb->getQuery()->execute();
	
	}
}
