<?php

namespace AppBundle\Repository;

/**
 * SearchFilterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchFilterRepository extends \Doctrine\ORM\EntityRepository
{
}
