# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    templating: value

services:
    app.listener.request:
        class: AppBundle\EventListener\RequestListener
        arguments: ['@twig', '@doctrine']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: provideTemplateTwigObjects }
    app.elasticsearch:
        class: Elasticsearch\ClientBuilder
        factory: [AppBundle\Factories\ElasticsearchClientBuilderFactory, build]
        arguments: [['http://localhost:9200']]
    app.twig.extension.stringloader:
        class: Twig_Extension_StringLoader
        tags:
             - { name: 'twig.extension' }
    app.form.ouuid:
        class: AppBundle\Form\OuuidType
        tags:
            - { name: form.type }
            - { name: ems.field.type }
    app.form.string:
        class: AppBundle\Form\StringType
        tags:
            - { name: form.type }
            - { name: ems.field.type }
