# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    templating: value

services:
    app.listener.request:
        class: AppBundle\EventListener\RequestListener
        arguments: ['@twig', '@doctrine']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: provideTemplateTwigObjects }
    app.elasticsearch:
        class: Elasticsearch\ClientBuilder
        factory: [AppBundle\Factories\ElasticsearchClientBuilderFactory, build]
        arguments: [['http://localhost:9200']]
    app.twig.extension.stringloader:
        class: Twig_Extension_StringLoader
        tags:
             - { name: 'twig.extension' }
    ems.form.view.keywords:
        class: AppBundle\Form\View\KeywordsViewType
        arguments: ['@twig', '@app.elasticsearch']
        tags:
            - { name: ems.form.viewtype, alias: keywords }
            - { name: form.type }
    ems.form.field.viewtypepickertype:
        class: AppBundle\Form\Field\ViewTypePickerType
        tags:
            - { name: form.type }