services:
    app.elasticsearch:
        class: Elasticsearch\ClientBuilder
        factory: [AppBundle\Factories\ElasticsearchClientBuilderFactory, build]
        arguments:
            - %elasticsearch_hosts%
    app.form.type.string:
        class: AppBundle\Form\DataField\TextFieldType
        tags:
            - { name: form.type }
            - { name: form.ems.DataField.type }
